name: "IO2MQTT"
version: "0.2.0"
slug: "io2mqtt"
image: "ghcr.io/ausf/{arch}-addon-io2mqtt"
description: "Run the last official version of MQTT-IO, adding a custom serial stream module"
url: "https://github.com/AUSF/HA-apps/tree/main/io2mqtt"
arch:
  - aarch64
  - amd64
  - armv7
startup: "services"
boot: "auto"
full_access: true
apparmor: false
gpio: true
uart: true
map:
  - config:rw
options:
  mqtt_io_config_path: "/config/mqtt-io/config.yml"
  log_level: "info"
schema:
  mqtt_io_config_path: "str"
  log_level: "list(debug|info|warning|error)"